// frontend/src/login-screen/Login.tsx
import React from "react";
import axios from "axios";
import UnauthorizedError from "./components/error/unauthorized-error";
import "./login.css";
import { CustomInput } from "../components/input/custom-input";

export function Login() {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState(false);

  const handleEmailCHange = (e: any) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: any) => {
    setPassword(e.target.value);
  };

  const handleFormSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    try {
      const response = await axios.post(`http://localhost:3000/login`, {
        email,
        password,
      });

      const authToken = response.data.access_token;
      localStorage.setItem("authToken", authToken);
    } catch (error) {
      setError(true);
    }
  };

  const loginDemoAccount = async (event: React.FormEvent) => {
    event.preventDefault();
    await axios.post(`http://localhost:3000/login`, {
      email: "demo@demo.com",
      password: "123456",
    });
  };

  return (
    <div id="main">
      <div id="login">
        {error && <UnauthorizedError />}
        <div id="loginTitle">Login</div>
        <form onSubmit={handleFormSubmit}>
          <CustomInput
            value={email}
            type="text"
            label="Email"
            onChange={handleEmailCHange}
          />
          <CustomInput
            value={password}
            type="password"
            label="Senha"
            onChange={handlePasswordChange}
          />
          <button type="submit" className="enter-button">
            Entrar
          </button>
          <p className="footer-text">
            Não tem uma conta?{" "}
            <a href="http://localhost:5173/signup">Criar conta</a>
          </p>
          <div className="footer">
            <div className="line"></div>
            <p className="account-demo">Ou</p>
            <div className="line"></div>
          </div>
          <button
            type="submit"
            className="demo-button"
            onClick={loginDemoAccount}
          >
            Entrar com conta demo
          </button>
        </form>
      </div>
    </div>
  );
}

// frontend-vue/src/Login-screen/Login.vue
<script>
import Input from "./components/Input-default.vue";
import Button from "./components/Input-button-submit.vue";
import Demo from "./components/Input-button-demo.vue";

export default {
  name: "Login",
  components: {
    Input,
    Button,
    Demo,
  },
  data() {
    return {
      value: "Entrar",
      demoValue: "Entrar com conta demo",
    };
  },
};
</script>

<template>
  <div id="container">
    <span id="title">Login</span>
    <div class="label-container">
      <label> Email </label>
      <Input class="input-default" type="email" />
    </div>

    <div class="label-container">
      <label> Senha</label>
      <Input class="input-default" type="password" />
    </div>

    <Button id="button-submit" :value="value" />
    <div>
      <span id="no-account">Não tem uma conta?</span>
      <a href="">Criar conta</a>
    </div>
    <div id="or">
      <div class="line"></div>
      Ou
      <div class="line"></div>
    </div>
    <Demo id="button-demo" :value="demoValue" />
  </div>
</template>

<style scoped>
#title {
  font-size: 32px;
  font-weight: bold;
}

#container {
  margin-top: 100px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 24px;
}

label {
  font-size: 16px;
}

.label-container {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

#no-account {
  color: #000;
  opacity: 0.5;
  margin-right: 6px;
}

a {
  color: #189ea7;
  text-decoration: none;
}

.line {
  width: 128px;
  height: 1px;
  background-color: #000;
  margin-left: 10px;
  margin-right: 10px;
}

#or {
  display: flex;
  align-items: center;
  opacity: 0.3;
}
</style>
